Started logging messages at Mon Apr 15 14:21:01 2019
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 6 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 68
Info:            Created 
Info:        Working on 69
Info:            Created 
Info:        Working on 88
Info:            Created 
Info:        Working on 89
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 84
Info:            Created 
Info:        Working on 100
Info:            Created 
Info:        Working on 14
Info:            Created 
Info:        Working on 97
Info:            Created 
Info:        Working on 105
Info:            Created 
Info:        Working on 19
Info:            Created 
Info:        Working on 28
Info:            Created 
Info:        Working on 47
Info:            Created 
Info:        Working on 71
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 3.26761e-005
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Mon Apr 15 14:21:01 2019
