Started logging messages at Thu Apr 18 01:29:43 2019
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 78 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 92
Info:            Created 
Info:        Working on 93
Info:            Created 
Info:        Working on 146
Info:            Created 
Info:        Working on 151
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 135
Info:            Created 
Info:        Working on 136
Info:            Created 
Info:        Working on 221
Info:            Created 
Info:        Working on 226
Info:            Created 
Info:        Working on 14
Info:            Created 
Info:        Working on 210
Info:            Created 
Info:        Working on 211
Info:            Created 
Info:        Working on 338
Info:            Created 
Info:        Working on 343
Info:            Created 
Info:        Working on 20
Info:            Created 
Info:        Working on 327
Info:            Created 
Info:        Working on 328
Info:            Created 
Info:        Working on 496
Info:            Created 
Info:        Working on 501
Info:            Created 
Info:        Working on 30
Info:            Created 
Info:        Working on 485
Info:            Created 
Info:        Working on 486
Info:            Created 
Info:        Working on 670
Info:            Created 
Info:        Working on 675
Info:            Created 
Info:        Working on 52
Info:            Created 
Info:        Working on 659
Info:            Created 
Info:        Working on 660
Info:            Created 
Info:        Working on 832
Info:            Created 
Info:        Working on 837
Info:            Created 
Info:        Working on 97
Info:            Created 
Info:        Working on 267
Info:            Created 
Info:        Working on 591
Info:            Created 
Info:        Working on 402
Info:            Created 
Info:        Working on 583
Info:            Created 
Info:        Working on 763
Info:            Created 
Info:        Working on 775
Info:            Created 
Info:        Working on 172
Info:            Created 
Info:        Working on 276
Info:            Created 
Info:        Working on 390
Info:            Created 
Info:        Working on 249
Info:            Created 
Info:        Working on 1055
Info:            Created 
Info:        Working on 1056
Info:            Created 
Info:        Working on 1179
Info:            Created 
Info:        Working on 1180
Info:            Created 
Info:        Working on 393
Info:            Created 
Info:        Working on 375
Info:            Created 
Info:        Working on 374
Info:            Created 
Info:        Working on 236
Info:            Created 
Info:        Working on 540
Info:            Created 
Info:        Working on 363
Info:            Created 
Info:        Working on 543
Info:            Created 
Info:        Working on 537
Info:            Created 
Info:        Working on 370
Info:            Created 
Info:        Working on 533
Info:            Created 
Info:        Working on 532
Info:            Created 
Info:        Working on 353
Info:            Created 
Info:        Working on 714
Info:            Created 
Info:        Working on 521
Info:            Created 
Info:        Working on 717
Info:            Created 
Info:        Working on 711
Info:            Created 
Info:        Working on 528
Info:            Created 
Info:        Working on 707
Info:            Created 
Info:        Working on 706
Info:            Created 
Info:        Working on 511
Info:            Created 
Info:        Working on 876
Info:            Created 
Info:        Working on 695
Info:            Created 
Info:        Working on 879
Info:            Created 
Info:        Working on 873
Info:            Created 
Info:        Working on 702
Info:            Created 
Info:        Working on 869
Info:            Created 
Info:        Working on 868
Info:            Created 
Info:        Working on 685
Info:            Created 
Info:        Working on 1015
Info:            Created 
Info:        Working on 857
Info:            Created 
Info:        Working on 1018
Info:            Created 
Info:        Working on 1012
Info:            Created 
Info:        Working on 864
Info:            Created 
Info:        Working on 1008
Info:            Created 
Info:        Working on 1007
Info:            Created 
Info:        Working on 847
Info:            Created 
Info:        Working on 1146
Info:            Created 
Info:        Working on 996
Info:            Created 
Info:        Working on 1149
Info:            Created 
Info:        Working on 1143
Info:            Created 
Info:        Working on 1004
Info:            Created 
Info:        Working on 1323
Info:            Created 
Info:        Working on 1467
Info:            Created 
Info:        Working on 1152
Info:            Created 
Info:        Working on 1197
Info:            Created 
Info:        Working on 1297
Info:            Created 
Info:        Working on 1468
Info:            Created 
Info:        Working on 1471
Info:            Created 
Info:        Working on 1317
Info:            Created 
Info:        Working on 1318
Info:            Created 
Info:        Working on 1446
Info:            Created 
Info:        Working on 1070
Info:            Created 
Info:        Working on 1076
Info:            Created 
Info:        Working on 1061
Info:            Created 
Info:        Working on 1208
Info:            Created 
Info:        Working on 1209
Info:            Created 
Info:        Working on 1192
Info:            Created 
Info:        Working on 1202
Info:            Created 
Info:        Working on 1328
Info:            Created 
Info:        Working on 432
Info:            Created 
Info:        Working on 731
Info:            Created 
Info:        Working on 621
Info:            Created 
Info:        Working on 1035
Info:            Created 
Info:        Working on 1034
Info:            Created 
Info:        Working on 1100
Info:            Created 
Info:        Working on 929
Info:            Created 
Info:        Working on 799
Info:            Created 
Info:        Working on 724
Info:            Created 
Info:        Working on 1097
Info:            Created 
Info:        Working on 962
Info:            Created 
Info:        Working on 947
Info:            Created 
Info:        Working on 787
Info:            Created 
Info:        Working on 885
Info:            Created 
Info:        Working on 1586
Info:            Created 
Info:        Working on 1490
Info:            Created 
Info:        Working on 1363
Info:            Created 
Info:        Working on 1487
Info:            Created 
Info:        Working on 1025
Info:            Created 
Info:        Working on 1648
Info:            Created 
Info:        Working on 1649
Info:            Created 
Info:        Working on 1669
Info:            Created 
Info:        Working on 1656
Info:            Created 
Info:        Working on 1158
Info:            Created 
Info:        Working on 1625
Info:            Created 
Info:        Working on 1662
Info:            Created 
Info:        Working on 1661
Info:            Created 
Info:        Working on 1626
Info:            Created 
Info:        Working on 1301
Info:            Created 
Info:        Working on 1558
Info:            Created 
Info:        Working on 1636
Info:            Created 
Info:        Working on 1633
Info:            Created 
Info:        Working on 1559
Info:            Created 
Info:        Working on 1450
Info:            Created 
Info:        Working on 1443
Info:            Created 
Info:        Working on 1569
Info:            Created 
Info:        Working on 1566
Info:            Created 
Info:        Working on 1444
Info:            Created 
Info:        Working on 1572
Info:            Created 
Info:        Working on 616
Info:            Created 
Info:        Working on 891
Info:            Created 
Info:        Working on 797
Info:            Created 
Info:        Working on 738
Info:            Created 
Info:        Working on 769
Info:            Created 
Info:        Working on 747
Info:            Created 
Info:        Working on 931
Info:            Created 
Info:        Working on 748
Info:            Created 
Info:        Working on 905
Info:            Created 
Info:        Working on 1037
Info:            Created 
Info:        Working on 629
Info:            Created 
Info:        Working on 601
Info:            Created 
Info:        Working on 944
Info:            Created 
Info:        Working on 420
Info:            Created 
Info:        Working on 786
Info:            Created 
Info:        Working on 607
Info:            Created 
Info:        Working on 1362
Info:            Created 
Info:        Working on 1492
Info:            Created 
Info:        Working on 791
Info:            Created 
Info:        Working on 1486
Info:            Created 
Info:        Working on 951
Info:            Created 
Info:        Working on 1592
Info:            Created 
Info:        Working on 1090
Info:            Created 
Info:        Working on 1213
Info:            Created 
Info:        Working on 1599
Info:            Created 
Info:        Working on 1602
Info:            Created 
Info:        Working on 1339
Info:            Created 
Info:        Working on 1512
Info:            Created 
Info:        Working on 1475
Info:            Created 
Info:        Working on 1513
Info:            Created 
Info:        Working on 1589
Info:            Created 
Info:        Working on 1651
Info:            Created 
Info:        Working on 1523
Info:            Created 
Info:        Working on 1528
Info:            Created 
Info:        Working on 1658
Info:            Created 
Info:        Working on 1396
Info:            Created 
Info:        Working on 1617
Info:            Created 
Info:        Working on 1397
Info:            Created 
Info:        Working on 1538
Info:            Created 
Info:        Working on 1622
Info:            Created 
Info:        Working on 1407
Info:            Created 
Info:        Working on 1412
Info:            Created 
Info:        Working on 1630
Info:            Created 
Info:        Working on 1266
Info:            Created 
Info:        Working on 1548
Info:            Created 
Info:        Working on 1267
Info:            Created 
Info:        Working on 1422
Info:            Created 
Info:        Working on 1555
Info:            Created 
Info:        Working on 1277
Info:            Created 
Info:        Working on 1282
Info:            Created 
Info:        Working on 1563
Info:            Created 
Info:        Working on 1139
Info:            Created 
Info:        Working on 1432
Info:            Created 
Info:        Working on 1140
Info:            Created 
Info:        Working on 1292
Info:            Created 
Info:        Working on 1439
Info:            Created 
Info:        Working on 624
Info:            Created 
Info:        Working on 958
Info:            Created 
Info:        Working on 955
Info:            Created 
Info:        Working on 815
Info:            Created 
Info:        Working on 814
Info:            Created 
Info:        Working on 387
Info:            Created 
Info:        Working on 448
Info:            Created 
Info:        Working on 569
Info:            Created 
Info:        Working on 449
Info:            Created 
Info:        Working on 170
Info:            Created 
Info:        Working on 291
Info:            Created 
Info:        Working on 451
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Thu Apr 18 01:29:43 2019
