Started logging messages at Thu Apr 18 11:39:51 2019
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 84 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 61
Info:            Created 
Info:        Working on 92
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 88
Info:            Created 
Info:        Working on 89
Info:            Created 
Info:        Working on 122
Info:            Created 
Info:        Working on 130
Info:            Created 
Info:        Working on 14
Info:            Created 
Info:        Working on 179
Info:            Created 
Info:        Working on 182
Info:            Created 
Info:        Working on 20
Info:            Created 
Info:        Working on 173
Info:            Created 
Info:        Working on 174
Info:            Created 
Info:        Working on 247
Info:            Created 
Info:        Working on 252
Info:            Created 
Info:        Working on 28
Info:            Created 
Info:        Working on 356
Info:            Created 
Info:        Working on 359
Info:            Created 
Info:        Working on 42
Info:            Created 
Info:        Working on 350
Info:            Created 
Info:        Working on 351
Info:            Created 
Info:        Working on 484
Info:            Created 
Info:        Working on 489
Info:            Created 
Info:        Working on 65
Info:            Created 
Info:        Working on 646
Info:            Created 
Info:        Working on 649
Info:            Created 
Info:        Working on 99
Info:            Created 
Info:        Working on 641
Info:            Created 
Info:        Working on 630
Info:            Created 
Info:        Working on 330
Info:            Created 
Info:        Working on 460
Info:            Created 
Info:        Working on 151
Info:            Created 
Info:        Working on 274
Info:            Created 
Info:        Working on 371
Info:            Created 
Info:        Working on 510
Info:            Created 
Info:        Working on 662
Info:            Created 
Info:        Working on 853
Info:            Created 
Info:        Working on 1092
Info:            Created 
Info:        Working on 1327
Info:            Created 
Info:        Working on 1505
Info:            Created 
Info:        Working on 1537
Info:            Created 
Info:        Working on 1128
Info:            Created 
Info:        Working on 1129
Info:            Created 
Info:        Working on 1461
Info:            Created 
Info:        Working on 1242
Info:            Created 
Info:        Working on 770
Info:            Created 
Info:        Working on 771
Info:            Created 
Info:        Working on 1178
Info:            Created 
Info:        Working on 1059
Info:            Created 
Info:        Working on 830
Info:            Created 
Info:        Working on 637
Info:            Created 
Info:        Working on 331
Info:            Created 
Info:        Working on 820
Info:            Created 
Info:        Working on 1049
Info:            Created 
Info:        Working on 1283
Info:            Created 
Info:        Working on 1429
Info:            Created 
Info:        Working on 1430
Info:            Created 
Info:        Working on 1378
Info:            Created 
Info:        Working on 1151
Info:            Created 
Info:        Working on 916
Info:            Created 
Info:        Working on 722
Info:            Created 
Info:        Working on 556
Info:            Created 
Info:        Working on 404
Info:            Created 
Info:        Working on 203
Info:            Created 
Info:        Working on 436
Info:            Created 
Info:        Working on 195
Info:            Created 
Info:        Working on 949
Info:            Created 
Info:        Working on 1176
Info:            Created 
Info:        Working on 284
Info:            Created 
Info:        Working on 1238
Info:            Created 
Info:        Working on 1398
Info:            Created 
Info:        Working on 408
Info:            Created 
Info:        Working on 1355
Info:            Created 
Info:        Working on 1558
Info:            Created 
Info:        Working on 561
Info:            Created 
Info:        Working on 1536
Info:            Created 
Info:        Working on 1675
Info:            Created 
Info:        Working on 731
Info:            Created 
Info:        Working on 1348
Info:            Created 
Info:        Working on 1661
Info:            Created 
Info:        Working on 936
Info:            Created 
Info:        Working on 1513
Info:            Created 
Info:        Working on 1317
Info:            Created 
Info:        Working on 1166
Info:            Created 
Info:        Working on 863
Info:            Created 
Info:        Working on 880
Info:            Created 
Info:        Working on 883
Info:            Created 
Info:        Working on 1645
Info:            Created 
Info:        Working on 1721
Info:            Created 
Info:        Working on 1111
Info:            Created 
Info:        Working on 1729
Info:            Created 
Info:        Working on 1754
Info:            Created 
Info:        Working on 1336
Info:            Created 
Info:        Working on 988
Info:            Created 
Info:        Working on 1457
Info:            Created 
Info:        Working on 1232
Info:            Created 
Info:        Working on 1301
Info:            Created 
Info:        Working on 1462
Info:            Created 
Info:        Working on 1296
Info:            Created 
Info:        Working on 1293
Info:            Created 
Info:        Working on 1472
Info:            Created 
Info:        Working on 1288
Info:            Created 
Info:        Working on 1484
Info:            Created 
Info:        Working on 1270
Info:            Created 
Info:        Working on 1481
Info:            Created 
Info:        Working on 793
Info:            Created 
Info:        Working on 449
Info:            Created 
Info:        Working on 610
Info:            Created 
Info:        Working on 1020
Info:            Created 
Info:        Working on 604
Info:            Created 
Info:        Working on 791
Info:            Created 
Info:        Working on 520
Info:            Created 
Info:        Working on 543
Info:            Created 
Info:        Working on 546
Info:            Created 
Info:        Working on 1549
Info:            Created 
Info:        Working on 1672
Info:            Created 
Info:        Working on 713
Info:            Created 
Info:        Working on 1695
Info:            Created 
Info:        Working on 1687
Info:            Created 
Info:        Working on 907
Info:            Created 
Info:        Working on 1591
Info:            Created 
Info:        Working on 1614
Info:            Created 
Info:        Working on 1140
Info:            Created 
Info:        Working on 1210
Info:            Created 
Info:        Working on 1551
Info:            Created 
Info:        Working on 1368
Info:            Created 
Info:        Working on 1153
Info:            Created 
Info:        Working on 932
Info:            Created 
Info:        Working on 923
Info:            Created 
Info:        Working on 1442
Info:            Created 
Info:        Working on 1164
Info:            Created 
Info:        Working on 1155
Info:            Created 
Info:        Working on 295
Info:            Created 
Info:        Working on 572
Info:            Created 
Info:        Working on 423
Info:            Created 
Info:        Working on 622
Info:            Created 
Info:        Working on 1040
Info:            Created 
Info:        Working on 575
Info:            Created 
Info:        Working on 1250
Info:            Created 
Info:        Working on 1487
Info:            Created 
Info:        Working on 748
Info:            Created 
Info:        Working on 1586
Info:            Created 
Info:        Working on 1692
Info:            Created 
Info:        Working on 956
Info:            Created 
Info:        Working on 1607
Info:            Created 
Info:        Working on 1226
Info:            Created 
Info:        Working on 1182
Info:            Created 
Info:        Working on 1543
Info:            Created 
Info:        Working on 1437
Info:            Created 
Info:        Working on 1402
Info:            Created 
Info:        Working on 1740
Info:            Created 
Info:        Working on 1525
Info:            Created 
Info:        Working on 1567
Info:            Created 
Info:        Working on 706
Info:            Created 
Info:        Working on 418
Info:            Created 
Info:        Working on 571
Info:            Created 
Info:        Working on 709
Info:            Created 
Info:        Working on 690
Info:            Created 
Info:        Working on 744
Info:            Created 
Info:        Working on 1498
Info:            Created 
Info:        Working on 1718
Info:            Created 
Info:        Working on 952
Info:            Created 
Info:        Working on 1099
Info:            Created 
Info:        Working on 1102
Info:            Created 
Info:        Working on 871
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 1759
Info:            Created 
Info:        Working on 1764
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 693
Info:            Created 
Info:        Working on 528
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 1655
Info:            Created 
Info:        Working on 1665
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 425
Info:            Created 
Info:        Working on 303
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 1450
Info:            Created 
Info:        Working on 1460
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 1598
Info:            Created 
Info:        Working on 1599
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 1469
Info:            Created 
Info:        Working on 1261
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 1691
Info:            Created 
Info:        Working on 1749
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 1587
Info:            Created 
Info:        Working on 752
Info:            Created 
Info:        Working on 1686
Info:            Created 
Info:        Working on 961
Info:            Created 
Info:        Working on 1187
Info:            Created 
Info:        Working on 806
Info:            Created 
Info:        Working on 1276
Info:            Created 
Info:        Working on 1039
Info:            Created 
Info:        Working on 1033
Info:            Created 
Info:        Working on 1475
Info:            Created 
Info:        Working on 1278
Info:            Created 
Info:        Working on 1275
Info:            Created 
Info:        Working on 1010
Info:            Created 
Info:        Working on 1466
Info:            Created 
Info:        Working on 784
Info:            Created 
Info:        Working on 1017
Info:            Created 
Info:        Working on 1258
Info:            Created 
Info:        Working on 1700
Info:            Created 
Info:        Working on 1471
Info:            Created 
Info:        Working on 1678
Info:            Created 
Info:        Working on 1611
Info:            Created 
Info:        Working on 1697
Info:            Created 
Info:        Working on 1771
Info:            Created 
Info:        Working on 1737
Info:            Created 
Info:        Working on 1772
Info:            Created 
Info:        Working on 1745
Info:            Created 
Info:        Working on 1768
Info:            Created 
Info:        Working on 1627
Info:            Created 
Info:        Working on 1717
Info:            Created 
Info:        Working on 1711
Info:            Created 
Info:        Working on 1761
Info:            Created 
Info:        Working on 1758
Info:            Created 
Info:        Working on 141
Info:            Created 
Info:        Working on 1107
Info:            Created 
Info:        Working on 1070
Info:            Created 
Info:        Working on 1308
Info:            Created 
Info:        Working on 1305
Info:            Created 
Info:        Working on 1077
Info:            Created 
Info:        Working on 1073
Info:            Created 
Info:        Working on 1307
Info:            Created 
Info:        Working on 874
Info:            Created 
Info:        Working on 1113
Info:            Created 
Info:        Working on 677
Info:            Created 
Info:        Working on 673
Info:            Created 
Info:        Working on 873
Info:            Created 
Info:        Working on 537
Info:            Created 
Info:        Working on 741
Info:            Created 
Info:        Working on 389
Info:            Created 
Info:        Working on 382
Info:            Created 
Info:        Working on 532
Info:            Created 
Info:        Working on 1544
Info:            Created 
Info:        Working on 703
Info:            Created 
Info:        Working on 1385
Info:            Created 
Info:        Working on 902
Info:            Created 
Info:        Working on 1132
Info:            Created 
Info:        Working on 95
Info:            Created 
Info:        Working on 144
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 5.22077e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Thu Apr 18 11:39:52 2019
